# Generated by Django 6.0.5 on 2026-08-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_systemsettings_remove_book_copies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='currency',
            field=models.CharField(choices=[('INR', 'Rupees (₹)'), ('USD', 'Dollars ($)')], default='INR', max_length=10),
        ),
    ]
